version: "3.1"

services:
    mysql:
      image: mysql:5.7
      container_name: wp-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=wp_test
        - MYSQL_USER=wp_user
        - MYSQL_PASSWORD=wp_pass
      ports:
        - "8889:3306"

    webserver:
      image: nginx:alpine
      container_name: wp-webserver
      working_dir: /application
      volumes:
          - ./wordpress:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/nginx/vhosts:/etc/nginx/conf.d
      ports:
        - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: wp-php-fpm
      working_dir: /application
      volumes:
        - ./wordpress:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      ports:
        - "8088:8088"
